(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          QUALIFIERSTEERINGANGLEFRONTAXLE-VAL
          QUALIFIERSTEERINGANGLEFRONTAXLE
          STEERINGANGLEFRONTAXLEERRAMP-VAL
          STEERINGANGLEFRONTAXLEERRAMP
          STEERINGANGLEFRONTAXLEERRAMP_INVALIDFLAG-VAL
          STEERINGANGLEFRONTAXLEERRAMP_INVALIDFLAG
          STEERINGANGLEFRONTAXLE-VAL
          STEERINGANGLEFRONTAXLE
          STEERINGANGLEFRONTAXLE_INVALIDFLAG-VAL
          STEERINGANGLEFRONTAXLE_INVALIDFLAG
          STEERINGANGLEFRONTAXLEEVENTDATAQUALIFIER-VAL
          STEERINGANGLEFRONTAXLEEVENTDATAQUALIFIER
))