(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATIONLONGITUDINALERRAMP-VAL
          ACCELERATIONLONGITUDINALERRAMP
          ACCELERATIONLONGITUDINALERRAMP_INVALIDFLAG-VAL
          ACCELERATIONLONGITUDINALERRAMP_INVALIDFLAG
          QUALIFIERACCELERATIONLONGITUDINAL-VAL
          QUALIFIERACCELERATIONLONGITUDINAL
          ACCELERATIONLONGITUDINAL-VAL
          ACCELERATIONLONGITUDINAL
          ACCELERATIONLONGITUDINAL_INVALIDFLAG-VAL
          ACCELERATIONLONGITUDINAL_INVALIDFLAG
          ACCELERATIONLONGITUDINALEVENTDATAQUALIFIER-VAL
          ACCELERATIONLONGITUDINALEVENTDATAQUALIFIER
))