(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          F_X-VAL
          F_X
          F_Y-VAL
          F_Y
          F_Z-VAL
          F_Z
          U_INVALIDFLAGS-VAL
          U_INVALIDFLAGS
          F_RANGERATE-VAL
          F_RANGERATE
          F_RANGERATESTD-VAL
          F_RANGERATESTD
          S_RCS-VAL
          S_RCS
          U_MEASUREMENTID-VAL
          U_MEASUREMENTID
          U_POSITIVEPREDICTIVEVALUE-VAL
          U_POSITIVEPREDICTIVEVALUE
          U_CLASSIFICATION-VAL
          U_CLASSIFICATION
          U_MULTITARGETPROBABILITY-VAL
          U_MULTITARGETPROBABILITY
          U_OBJECTID-VAL
          U_OBJECTID
          U_AMBIGUITYFLAG-VAL
          U_AMBIGUITYFLAG
          U_SORTINDEX-VAL
          U_SORTINDEX
))