(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATUSVELOCITYNEARSTANDSTILL-VAL
          STATUSVELOCITYNEARSTANDSTILL
          QUALIFIERVELOCITYVEHICLE-VAL
          QUALIFIERVELOCITYVEHICLE
          VELOCITYVEHICLEEVENTDATAQUALIFIER-VAL
          VELOCITYVEHICLEEVENTDATAQUALIFIER
          VELOCITYVEHICLE-VAL
          VELOCITYVEHICLE
          VELOCITYVEHICLE_INVALIDFLAG-VAL
          VELOCITYVEHICLE_INVALIDFLAG
))