(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATIONLATERALERRAMP-VAL
          ACCELERATIONLATERALERRAMP
          ACCELERATIONLATERALERRAMP_INVALIDFLAG-VAL
          ACCELERATIONLATERALERRAMP_INVALIDFLAG
          QUALIFIERACCELERATIONLATERAL-VAL
          QUALIFIERACCELERATIONLATERAL
          ACCELERATIONLATERAL-VAL
          ACCELERATIONLATERAL
          ACCELERATIONLATERAL_INVALIDFLAG-VAL
          ACCELERATIONLATERAL_INVALIDFLAG
          ACCELERATIONLATERALEVENTDATAQUALIFIER-VAL
          ACCELERATIONLATERALEVENTDATAQUALIFIER
))