(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRIVINGDIRECTIONUNCONFIRMED-VAL
          DRIVINGDIRECTIONUNCONFIRMED
          DRIVINGDIRECTIONCONFIRMED-VAL
          DRIVINGDIRECTIONCONFIRMED
))