(cl:in-package ars548_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          CHARACTERISTICSPEEDERRAMP-VAL
          CHARACTERISTICSPEEDERRAMP
          QUALIFIERCHARACTERISTICSPEED-VAL
          QUALIFIERCHARACTERISTICSPEED
          CHARACTERISTICSPEED-VAL
          CHARACTERISTICSPEED
))