(cl:defpackage ars548_msg-msg
  (:use )
  (:export
   "<ACCELERATIONLATERALCOG>"
   "ACCELERATIONLATERALCOG"
   "<ACCELERATIONLONGITUDINALCOG>"
   "ACCELERATIONLONGITUDINALCOG"
   "<CHARACTERISTICSPEED>"
   "CHARACTERISTICSPEED"
   "<DETECTIONLIST>"
   "DETECTIONLIST"
   "<DRIVINGDIRECTION>"
   "DRIVINGDIRECTION"
   "<OBJECTLIST>"
   "OBJECTLIST"
   "<RADARBASICSTATUS>"
   "RADARBASICSTATUS"
   "<STEERINGANGLEFRONTAXLE>"
   "STEERINGANGLEFRONTAXLE"
   "<VELOCITYVEHICLE>"
   "VELOCITYVEHICLE"
   "<YAWRATE>"
   "YAWRATE"
   "<DETECTIONS>"
   "DETECTIONS"
   "<OBJECTS>"
   "OBJECTS"
  ))

