# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ars548_msg/AccelerationLateralCog.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class AccelerationLateralCog(genpy.Message):
  _md5sum = "309ffa6c4255f866c5f325a81d5d71f4"
  _type = "ars548_msg/AccelerationLateralCog"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

float32 AccelerationLateralErrAmp
uint8 AccelerationLateralErrAmp_InvalidFlag
uint8 QualifierAccelerationLateral 
float32 AccelerationLateral
uint8 AccelerationLateral_InvalidFlag
uint8 AccelerationLateralEventDataQualifier


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','AccelerationLateralErrAmp','AccelerationLateralErrAmp_InvalidFlag','QualifierAccelerationLateral','AccelerationLateral','AccelerationLateral_InvalidFlag','AccelerationLateralEventDataQualifier']
  _slot_types = ['std_msgs/Header','float32','uint8','uint8','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,AccelerationLateralErrAmp,AccelerationLateralErrAmp_InvalidFlag,QualifierAccelerationLateral,AccelerationLateral,AccelerationLateral_InvalidFlag,AccelerationLateralEventDataQualifier

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AccelerationLateralCog, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.AccelerationLateralErrAmp is None:
        self.AccelerationLateralErrAmp = 0.
      if self.AccelerationLateralErrAmp_InvalidFlag is None:
        self.AccelerationLateralErrAmp_InvalidFlag = 0
      if self.QualifierAccelerationLateral is None:
        self.QualifierAccelerationLateral = 0
      if self.AccelerationLateral is None:
        self.AccelerationLateral = 0.
      if self.AccelerationLateral_InvalidFlag is None:
        self.AccelerationLateral_InvalidFlag = 0
      if self.AccelerationLateralEventDataQualifier is None:
        self.AccelerationLateralEventDataQualifier = 0
    else:
      self.header = std_msgs.msg.Header()
      self.AccelerationLateralErrAmp = 0.
      self.AccelerationLateralErrAmp_InvalidFlag = 0
      self.QualifierAccelerationLateral = 0
      self.AccelerationLateral = 0.
      self.AccelerationLateral_InvalidFlag = 0
      self.AccelerationLateralEventDataQualifier = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2Bf2B().pack(_x.AccelerationLateralErrAmp, _x.AccelerationLateralErrAmp_InvalidFlag, _x.QualifierAccelerationLateral, _x.AccelerationLateral, _x.AccelerationLateral_InvalidFlag, _x.AccelerationLateralEventDataQualifier))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.AccelerationLateralErrAmp, _x.AccelerationLateralErrAmp_InvalidFlag, _x.QualifierAccelerationLateral, _x.AccelerationLateral, _x.AccelerationLateral_InvalidFlag, _x.AccelerationLateralEventDataQualifier,) = _get_struct_f2Bf2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2Bf2B().pack(_x.AccelerationLateralErrAmp, _x.AccelerationLateralErrAmp_InvalidFlag, _x.QualifierAccelerationLateral, _x.AccelerationLateral, _x.AccelerationLateral_InvalidFlag, _x.AccelerationLateralEventDataQualifier))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.AccelerationLateralErrAmp, _x.AccelerationLateralErrAmp_InvalidFlag, _x.QualifierAccelerationLateral, _x.AccelerationLateral, _x.AccelerationLateral_InvalidFlag, _x.AccelerationLateralEventDataQualifier,) = _get_struct_f2Bf2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_f2Bf2B = None
def _get_struct_f2Bf2B():
    global _struct_f2Bf2B
    if _struct_f2Bf2B is None:
        _struct_f2Bf2B = struct.Struct("<f2Bf2B")
    return _struct_f2Bf2B
