// Generated by gencpp from file ars548_msg/CharacteristicSpeed.msg
// DO NOT EDIT!


#ifndef ARS548_MSG_MESSAGE_CHARACTERISTICSPEED_H
#define ARS548_MSG_MESSAGE_CHARACTERISTICSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ars548_msg
{
template <class ContainerAllocator>
struct CharacteristicSpeed_
{
  typedef CharacteristicSpeed_<ContainerAllocator> Type;

  CharacteristicSpeed_()
    : header()
    , CharacteristicSpeedErrAmp(0)
    , QualifierCharacteristicSpeed(0)
    , CharacteristicSpeed(0)  {
    }
  CharacteristicSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , CharacteristicSpeedErrAmp(0)
    , QualifierCharacteristicSpeed(0)
    , CharacteristicSpeed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _CharacteristicSpeedErrAmp_type;
  _CharacteristicSpeedErrAmp_type CharacteristicSpeedErrAmp;

   typedef uint8_t _QualifierCharacteristicSpeed_type;
  _QualifierCharacteristicSpeed_type QualifierCharacteristicSpeed;

   typedef uint8_t _CharacteristicSpeed_type;
  _CharacteristicSpeed_type CharacteristicSpeed;





  typedef boost::shared_ptr< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct CharacteristicSpeed_

typedef ::ars548_msg::CharacteristicSpeed_<std::allocator<void> > CharacteristicSpeed;

typedef boost::shared_ptr< ::ars548_msg::CharacteristicSpeed > CharacteristicSpeedPtr;
typedef boost::shared_ptr< ::ars548_msg::CharacteristicSpeed const> CharacteristicSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator1> & lhs, const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.CharacteristicSpeedErrAmp == rhs.CharacteristicSpeedErrAmp &&
    lhs.QualifierCharacteristicSpeed == rhs.QualifierCharacteristicSpeed &&
    lhs.CharacteristicSpeed == rhs.CharacteristicSpeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator1> & lhs, const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ars548_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a76f81f56c6194220c9fac0cf9adb10e";
  }

  static const char* value(const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa76f81f56c619422ULL;
  static const uint64_t static_value2 = 0x0c9fac0cf9adb10eULL;
};

template<class ContainerAllocator>
struct DataType< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ars548_msg/CharacteristicSpeed";
  }

  static const char* value(const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 CharacteristicSpeedErrAmp\n"
"uint8 QualifierCharacteristicSpeed\n"
"uint8 CharacteristicSpeed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.CharacteristicSpeedErrAmp);
      stream.next(m.QualifierCharacteristicSpeed);
      stream.next(m.CharacteristicSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CharacteristicSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ars548_msg::CharacteristicSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ars548_msg::CharacteristicSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "CharacteristicSpeedErrAmp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CharacteristicSpeedErrAmp);
    s << indent << "QualifierCharacteristicSpeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.QualifierCharacteristicSpeed);
    s << indent << "CharacteristicSpeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CharacteristicSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARS548_MSG_MESSAGE_CHARACTERISTICSPEED_H
