// Generated by gencpp from file ars548_msg/VelocityVehicle.msg
// DO NOT EDIT!


#ifndef ARS548_MSG_MESSAGE_VELOCITYVEHICLE_H
#define ARS548_MSG_MESSAGE_VELOCITYVEHICLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ars548_msg
{
template <class ContainerAllocator>
struct VelocityVehicle_
{
  typedef VelocityVehicle_<ContainerAllocator> Type;

  VelocityVehicle_()
    : header()
    , StatusVelocityNearStandstill(0)
    , QualifierVelocityVehicle(0)
    , VelocityVehicleEventDataQualifier(0)
    , VelocityVehicle(0.0)
    , VelocityVehicle_InvalidFlag(0)  {
    }
  VelocityVehicle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , StatusVelocityNearStandstill(0)
    , QualifierVelocityVehicle(0)
    , VelocityVehicleEventDataQualifier(0)
    , VelocityVehicle(0.0)
    , VelocityVehicle_InvalidFlag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _StatusVelocityNearStandstill_type;
  _StatusVelocityNearStandstill_type StatusVelocityNearStandstill;

   typedef uint8_t _QualifierVelocityVehicle_type;
  _QualifierVelocityVehicle_type QualifierVelocityVehicle;

   typedef uint8_t _VelocityVehicleEventDataQualifier_type;
  _VelocityVehicleEventDataQualifier_type VelocityVehicleEventDataQualifier;

   typedef float _VelocityVehicle_type;
  _VelocityVehicle_type VelocityVehicle;

   typedef uint8_t _VelocityVehicle_InvalidFlag_type;
  _VelocityVehicle_InvalidFlag_type VelocityVehicle_InvalidFlag;





  typedef boost::shared_ptr< ::ars548_msg::VelocityVehicle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ars548_msg::VelocityVehicle_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityVehicle_

typedef ::ars548_msg::VelocityVehicle_<std::allocator<void> > VelocityVehicle;

typedef boost::shared_ptr< ::ars548_msg::VelocityVehicle > VelocityVehiclePtr;
typedef boost::shared_ptr< ::ars548_msg::VelocityVehicle const> VelocityVehicleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ars548_msg::VelocityVehicle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ars548_msg::VelocityVehicle_<ContainerAllocator1> & lhs, const ::ars548_msg::VelocityVehicle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.StatusVelocityNearStandstill == rhs.StatusVelocityNearStandstill &&
    lhs.QualifierVelocityVehicle == rhs.QualifierVelocityVehicle &&
    lhs.VelocityVehicleEventDataQualifier == rhs.VelocityVehicleEventDataQualifier &&
    lhs.VelocityVehicle == rhs.VelocityVehicle &&
    lhs.VelocityVehicle_InvalidFlag == rhs.VelocityVehicle_InvalidFlag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ars548_msg::VelocityVehicle_<ContainerAllocator1> & lhs, const ::ars548_msg::VelocityVehicle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ars548_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::VelocityVehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::VelocityVehicle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::VelocityVehicle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd64397f65309febc4a646745760bb30";
  }

  static const char* value(const ::ars548_msg::VelocityVehicle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd64397f65309febULL;
  static const uint64_t static_value2 = 0xc4a646745760bb30ULL;
};

template<class ContainerAllocator>
struct DataType< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ars548_msg/VelocityVehicle";
  }

  static const char* value(const ::ars548_msg::VelocityVehicle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 StatusVelocityNearStandstill\n"
"uint8 QualifierVelocityVehicle\n"
"uint8 VelocityVehicleEventDataQualifier\n"
"float32 VelocityVehicle\n"
"uint8 VelocityVehicle_InvalidFlag\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ars548_msg::VelocityVehicle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.StatusVelocityNearStandstill);
      stream.next(m.QualifierVelocityVehicle);
      stream.next(m.VelocityVehicleEventDataQualifier);
      stream.next(m.VelocityVehicle);
      stream.next(m.VelocityVehicle_InvalidFlag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityVehicle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ars548_msg::VelocityVehicle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ars548_msg::VelocityVehicle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "StatusVelocityNearStandstill: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.StatusVelocityNearStandstill);
    s << indent << "QualifierVelocityVehicle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.QualifierVelocityVehicle);
    s << indent << "VelocityVehicleEventDataQualifier: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.VelocityVehicleEventDataQualifier);
    s << indent << "VelocityVehicle: ";
    Printer<float>::stream(s, indent + "  ", v.VelocityVehicle);
    s << indent << "VelocityVehicle_InvalidFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.VelocityVehicle_InvalidFlag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARS548_MSG_MESSAGE_VELOCITYVEHICLE_H
