// Generated by gencpp from file ars548_msg/YawRate.msg
// DO NOT EDIT!


#ifndef ARS548_MSG_MESSAGE_YAWRATE_H
#define ARS548_MSG_MESSAGE_YAWRATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ars548_msg
{
template <class ContainerAllocator>
struct YawRate_
{
  typedef YawRate_<ContainerAllocator> Type;

  YawRate_()
    : header()
    , YawRateErrAmp(0.0)
    , YawRateErrAmp_InvalidFlag(0)
    , QualifierYawRate(0)
    , YawRate(0.0)
    , YawRate_InvalidFlag(0)
    , YawRateEventDataQualifier(0)  {
    }
  YawRate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , YawRateErrAmp(0.0)
    , YawRateErrAmp_InvalidFlag(0)
    , QualifierYawRate(0)
    , YawRate(0.0)
    , YawRate_InvalidFlag(0)
    , YawRateEventDataQualifier(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _YawRateErrAmp_type;
  _YawRateErrAmp_type YawRateErrAmp;

   typedef uint8_t _YawRateErrAmp_InvalidFlag_type;
  _YawRateErrAmp_InvalidFlag_type YawRateErrAmp_InvalidFlag;

   typedef uint8_t _QualifierYawRate_type;
  _QualifierYawRate_type QualifierYawRate;

   typedef float _YawRate_type;
  _YawRate_type YawRate;

   typedef uint8_t _YawRate_InvalidFlag_type;
  _YawRate_InvalidFlag_type YawRate_InvalidFlag;

   typedef uint8_t _YawRateEventDataQualifier_type;
  _YawRateEventDataQualifier_type YawRateEventDataQualifier;





  typedef boost::shared_ptr< ::ars548_msg::YawRate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ars548_msg::YawRate_<ContainerAllocator> const> ConstPtr;

}; // struct YawRate_

typedef ::ars548_msg::YawRate_<std::allocator<void> > YawRate;

typedef boost::shared_ptr< ::ars548_msg::YawRate > YawRatePtr;
typedef boost::shared_ptr< ::ars548_msg::YawRate const> YawRateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ars548_msg::YawRate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ars548_msg::YawRate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ars548_msg::YawRate_<ContainerAllocator1> & lhs, const ::ars548_msg::YawRate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.YawRateErrAmp == rhs.YawRateErrAmp &&
    lhs.YawRateErrAmp_InvalidFlag == rhs.YawRateErrAmp_InvalidFlag &&
    lhs.QualifierYawRate == rhs.QualifierYawRate &&
    lhs.YawRate == rhs.YawRate &&
    lhs.YawRate_InvalidFlag == rhs.YawRate_InvalidFlag &&
    lhs.YawRateEventDataQualifier == rhs.YawRateEventDataQualifier;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ars548_msg::YawRate_<ContainerAllocator1> & lhs, const ::ars548_msg::YawRate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ars548_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::YawRate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::YawRate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::YawRate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::YawRate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::YawRate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::YawRate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ars548_msg::YawRate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d2890493281102c9697b6ad452e703b";
  }

  static const char* value(const ::ars548_msg::YawRate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d2890493281102cULL;
  static const uint64_t static_value2 = 0x9697b6ad452e703bULL;
};

template<class ContainerAllocator>
struct DataType< ::ars548_msg::YawRate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ars548_msg/YawRate";
  }

  static const char* value(const ::ars548_msg::YawRate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ars548_msg::YawRate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 YawRateErrAmp\n"
"uint8 YawRateErrAmp_InvalidFlag\n"
"uint8 QualifierYawRate\n"
"float32 YawRate\n"
"uint8 YawRate_InvalidFlag\n"
"uint8 YawRateEventDataQualifier\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ars548_msg::YawRate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ars548_msg::YawRate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.YawRateErrAmp);
      stream.next(m.YawRateErrAmp_InvalidFlag);
      stream.next(m.QualifierYawRate);
      stream.next(m.YawRate);
      stream.next(m.YawRate_InvalidFlag);
      stream.next(m.YawRateEventDataQualifier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YawRate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ars548_msg::YawRate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ars548_msg::YawRate_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "YawRateErrAmp: ";
    Printer<float>::stream(s, indent + "  ", v.YawRateErrAmp);
    s << indent << "YawRateErrAmp_InvalidFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.YawRateErrAmp_InvalidFlag);
    s << indent << "QualifierYawRate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.QualifierYawRate);
    s << indent << "YawRate: ";
    Printer<float>::stream(s, indent + "  ", v.YawRate);
    s << indent << "YawRate_InvalidFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.YawRate_InvalidFlag);
    s << indent << "YawRateEventDataQualifier: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.YawRateEventDataQualifier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARS548_MSG_MESSAGE_YAWRATE_H
